// Copies the compiled ABI into the web app at lib/arctounon-nft.ts.
// Usage: node scripts/export-abi.cjs <deployedAddress>
const fs = require("fs");
const path = require("path");

const artifact = require("../artifacts/contracts/ArctounonNFT.sol/ArctounonNFT.json");
const ADDRESS = process.argv[2] || "0x0000000000000000000000000000000000000000";

const out = `// AUTO-GENERATED by contracts/scripts/export-abi.cjs — do not edit by hand.
// Re-run after changing the contract:  node scripts/export-abi.cjs <address>
// On-chain interface for the Arctounon NFT (ERC721A) on Arc.

export const ZERO_ADDRESS =
  "0x0000000000000000000000000000000000000000" as const;

// Deployed address. Overridable at build time via NEXT_PUBLIC_ARCTOUNON_NFT_ADDRESS.
export const ARCTOUNON_NFT_ADDRESS = (process.env
  .NEXT_PUBLIC_ARCTOUNON_NFT_ADDRESS ?? "${ADDRESS}") as \`0x\${string}\`;

// True once a real contract address is wired in.
export const isNftConfigured = ARCTOUNON_NFT_ADDRESS !== ZERO_ADDRESS;

// Full compiled ABI. \`as const\` keeps wagmi/viem type-safe on args + returns.
export const arctounonNftAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

const dest = path.join(__dirname, "..", "..", "lib", "arctounon-nft.ts");
fs.writeFileSync(dest, out);
console.log(`Wrote ${dest}`);
console.log(`  ${artifact.abi.length} ABI entries, address ${ADDRESS}`);
